### ISSUE TITLE
Gamble all ajos

### ISSUE THREAD

**Issue by pakitometal** [ass-a-service/ajobot#38]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

`/gamble` command lacks an "all in" option to, well, gamble all ajos an user have in a single shot (instead of querying for ajo amount and passing it to gamble command)

### Describe the solution you'd like.

Something like `/gamble all`, which will gamble all ajos the user issuing the command has.

**Comment by axl89** [comment]
@pakitometal that looks like an awesome feature, thanks! It would be nice if you could do it, because this is open source and to be completely honest with you we're super lazy and tired. So:

- https://github.com/ass-a-service/ajobot/blob/master/src/lua/gamble.lua
- https://github.com/ass-a-service/ajobot/blob/master/src/impl/ajo/manager.py#L95
- https://github.com/ass-a-service/ajobot/blob/master/src/exts/ajo.py#L77

Thanks!
